services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=maxwellhay.com
      - NGINX_PORT=80
    volumes:
      - ./:/usr/share/nginx:ro
      - ./nginx-conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/letsencrypt:ro
    restart: unless-stopped

  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./cloudflare.ini:/etc/cloudflare.ini:ro
    command: >
      certonly --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare.ini
      --preferred-challenges dns-01
      --email mhay@uccs.edu --agree-tos --no-eff-email
      -d maxwellhay.com -d *.maxwellhay.com

  project-client:
    image: node:current-alpine
    container_name: project-client
    working_dir: /app
    volumes:
      - ./project/client:/app
    command: sh -c "npm install && npm run build"

  project-server:
    image: node:current-alpine
    container_name: project-server
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./project:/app
    command: sh -c "cd server && npm install && npm run build && npm start"
    restart: unless-stopped
