services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    container_name: cloudflared
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 10000:80 
    environment:
      - NGINX_HOST=maxwellhay.com
      - NGINX_PORT=80
    volumes:
      - ./:/usr/share/nginx:ro
      - ./nginx-conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped

  project:
    image: node:current-alpine
    container_name: project
    working_dir: /app
    volumes:
      - ./project:/app
    command: sh -c "npm install && npm run build"
